(function(root){'use strict';const MS=root.MarxSim=root.MarxSim||{};
function snapshot(state){const active=state.firms.filter(f=>f.active),population=state.households.reduce((s,h)=>s+h.population,0),employment=active.reduce((s,f)=>s+f.employees,0),output=active.reduce((s,f)=>s+f.output,0),profit=active.reduce((s,f)=>s+f.profit,0),inventory=active.reduce((s,f)=>s+f.inventory,0),rent=state.households.reduce((s,h)=>s+(h.rent||0),0),maxHhi=Object.values(state.economy.concentration||{}).reduce((m,x)=>Math.max(m,x.hhi||0),0);return {population,employment,unemploymentRate:state.economy.unemploymentRate||0,averageWage:state.economy.averageWage||0,output,profit,inventory,rent,maxHhi,organization:state.politics?state.politics.organization||0:0,discontent:state.politics?state.politics.discontent||0:0};}
function eventReason(type){return ({bankruptcy:'Betrieb geschlossen',acquisition:'Insolvente Kapazität übernommen',rationalization:'Technische Rationalisierung',firm_founded:'Neuer Betrieb gegründet',strike_started:'Streik begonnen',strike_ended:'Arbeitskampf beendet',household_moved:'Haushalte umgezogen',housing_built:'Wohnraum geschaffen',infrastructure_built:'Infrastruktur fertiggestellt',policy_enacted:'Reform beschlossen'})[type]||String(type||'Strukturereignis').replaceAll('_',' ');}
function likelyMetric(type){return ({bankruptcy:'unemploymentRate',rationalization:'employment',strike_started:'output',strike_ended:'output',firm_founded:'employment',household_moved:'rent',housing_built:'rent',infrastructure_built:'rent',policy_enacted:'discontent'})[type]||'structure';}
MS.beginCausalTick=function(state){state._causalSnapshot=snapshot(state);state._causalEventCursor=state.events.length;};
MS.recordCause=function(state,record){state.causalLog=state.causalLog||[];const item=Object.assign({id:`c${state.tick}-${state.causalLog.length+1}`,tick:state.tick,metric:'structure',delta:0,sourceType:'system',sourceId:'economy',reason:'Systemänderung',parentCause:null},record||{});state.causalLog.push(item);return item.id;};
MS.finalizeCausalTick=function(state){if(!state._causalSnapshot)return;const before=state._causalSnapshot,after=snapshot(state),newEvents=state.events.slice(state._causalEventCursor||0),parents={};newEvents.slice(-12).forEach((e,i)=>{const id=MS.recordCause(state,{id:`e${state.tick}-${i}`,metric:likelyMetric(e.type),delta:0,sourceType:e.firmId||e.buyerId?'firm':'event',sourceId:e.firmId||e.buyerId||e.districtId||e.policy||e.type,reason:eventReason(e.type),parentCause:null,eventType:e.type});parents[likelyMetric(e.type)]=parents[likelyMetric(e.type)]||id;});
const deltas=[['population',after.population-before.population],['employment',after.employment-before.employment],['unemploymentRate',after.unemploymentRate-before.unemploymentRate],['averageWage',after.averageWage-before.averageWage],['output',after.output-before.output],['profit',after.profit-before.profit],['inventory',after.inventory-before.inventory],['rent',after.rent-before.rent],['concentration',after.maxHhi-before.maxHhi],['organization',after.organization-before.organization],['discontent',after.discontent-before.discontent]];deltas.forEach(([metric,delta])=>{const scale=Math.max(1,Math.abs(before[metric]||0));if(Math.abs(delta)<Math.max(1e-6,scale*1e-5))return;let reason='Veränderung aus dem gekoppelten Wirtschaftszyklus';if(metric==='unemploymentRate')reason=delta>0?'Beschäftigung wächst langsamer als Arbeitsangebot':'Beschäftigung absorbiert Arbeitsangebot';if(metric==='averageWage')reason=delta>0?'Knappheit und Lohnangebote erhöhen den Durchschnitt':'Arbeitsmarkt- und Lohndruck senken den Durchschnitt';if(metric==='rent')reason=delta>0?'Wohnungsnachfrage erhöht den Mietdruck':'Neue Kapazität oder Abwanderung entlastet den Wohnungsmarkt';if(metric==='concentration')reason=delta>0?'Marktanteile konzentrieren sich':'Marktanteile verteilen sich breiter';if(metric==='organization')reason=delta>0?'Gemeinsame Betriebserfahrung und Konflikte stärken Organisation':'Schwacher Konfliktdruck lässt Organisation nach';MS.recordCause(state,{metric,delta,sourceType:'system',sourceId:metric,reason,parentCause:parents[metric]||null});});
const cutoff=Math.max(0,state.tick-240);state.causalLog=state.causalLog.filter(c=>c.tick>=cutoff);delete state._causalSnapshot;delete state._causalEventCursor;};
MS.getCausalSnapshot=snapshot;
})(typeof globalThis!=='undefined'?globalThis:window);
