(function(root){'use strict';const MS=root.MarxSim; if(!MS||!root.document) return;
  const state=MS.createGameState(root.MARXSIM_SCENARIO,1850); MS.initializeSpatialState(state); MS.updateSpatialEconomy(state); root.MarxSimGame=state;
  let speed=0, timer=null, layer='industry';
  const $=id=>document.getElementById(id), svg=$('rotfeld-map');
  function fmt(v,d=0){return Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d});}
  function districtPanel(){const d=state.districts.find(x=>x.id===state.map.selectedDistrict)||state.districts[0]; $('district-title').textContent=d.name; $('district-copy').innerHTML=`<dl><dt>Einwohner</dt><dd>${fmt(d.residents)}</dd><dt>Arbeitsangebot</dt><dd>${fmt(d.labor_supply)}</dd><dt>Arbeitsplätze</dt><dd>${fmt(d.jobs)}</dd><dt>Produktivkapital</dt><dd>${fmt(d.capital,1)}</dd><dt>Zugang</dt><dd>${fmt(d.access*100)} / 100</dd><dt>Wohnungsdruck</dt><dd>${fmt(d.housing_pressure*100)} %</dd></dl>`;}
  function events(){const list=$('event-log'); list.innerHTML=state.events.slice(-5).reverse().map(e=>`<li><span>${state.date.year}</span>${String(e.type).replaceAll('_',' ')}</li>`).join('')||'<li class="quiet">Noch keine Strukturereignisse.</li>';}
  function render(){MS.updateSpatialEconomy(state); MS.renderRotfeldMap(svg,state,layer); const m=state.metrics.history.at(-1)||{}; $('date').textContent=`${String(state.date.month).padStart(2,'0')} / ${state.date.year}`; $('population').textContent=fmt(state.households.reduce((s,h)=>s+h.population,0)); $('employment').textContent=fmt(state.firms.filter(f=>f.active).reduce((s,f)=>s+f.employees,0)); $('unemployment').textContent=fmt(state.economy.unemploymentRate*100,1)+' %'; $('wage').textContent=fmt(state.economy.averageWage,2); $('firms').textContent=state.firms.filter(f=>f.active).length; $('capital').textContent=fmt(m.capital||state.firms.reduce((s,f)=>s+(f.active?f.capital_stock:0),0)); districtPanel(); events();}
  function setSpeed(n){speed=n; document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===n)); if(timer) clearInterval(timer); timer=null; if(n>0) timer=setInterval(()=>{MS.runTicks(state,n);render();},900);}
  document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>setSpeed(Number(b.dataset.speed))));
  document.querySelectorAll('[data-layer]').forEach(b=>b.addEventListener('click',()=>{layer=b.dataset.layer;document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b));render();}));
  root.addEventListener('marxsim:district-selected',districtPanel); $('step').addEventListener('click',()=>{MS.simulateTick(state);render();}); render();
})(typeof globalThis!=='undefined'?globalThis:window);
