(function(root){'use strict';const MS=root.MarxSim=root.MarxSim||{},SAVE_KEY='marxsim.save.v1';MS.SAVE_SCHEMA=1;
function cleanState(state){return JSON.parse(JSON.stringify(state,(k,v)=>k.startsWith('_')?undefined:v));}
MS.serializeState=function(state,pretty){if(!state||!state.scenarioId)throw new Error('Ungültiger Spielstand');return JSON.stringify({schema:MS.SAVE_SCHEMA,game:'MARXSIM',savedAt:new Date().toISOString(),state:cleanState(state)},null,pretty?2:0);};
MS.deserializeState=function(text){const payload=typeof text==='string'?JSON.parse(text):text;if(!payload||payload.game!=='MARXSIM'||payload.schema!==MS.SAVE_SCHEMA||!payload.state)throw new Error('Nicht unterstützter MARXSIM-Spielstand');const s=payload.state;if(!Number.isInteger(s.tick)||!Number.isFinite(s.rngState)||!Array.isArray(s.firms)||!Array.isArray(s.households)||!s.metrics)throw new Error('Spielstand ist unvollständig');s.theory=s.theory||{seen:{}};s.causalLog=s.causalLog||[];s.events=s.events||[];s.map=s.map||{initialized:false,parcels:[]};return s;};
MS.saveLocal=function(state,storage){const target=storage||(root.localStorage||null);if(!target)throw new Error('localStorage nicht verfügbar');target.setItem(SAVE_KEY,MS.serializeState(state,false));return true;};
MS.loadLocal=function(storage){const target=storage||(root.localStorage||null);if(!target)return null;const text=target.getItem(SAVE_KEY);return text?MS.deserializeState(text):null;};
MS.clearLocalSave=function(storage){const target=storage||(root.localStorage||null);if(target)target.removeItem(SAVE_KEY);};
MS.downloadState=function(state){if(!root.document||!root.Blob||!root.URL)return MS.serializeState(state,true);const blob=new Blob([MS.serializeState(state,true)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`marxsim-${state.date.year}-${String(state.date.month).padStart(2,'0')}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),0);return true;};
})(typeof globalThis!=='undefined'?globalThis:window);
