(function(root){'use strict';const MS=root.MarxSim=root.MarxSim||{},clone=x=>JSON.parse(JSON.stringify(x));
MS.POLICY_PRESETS={laissezFaire:function(){},socialSpending:function(s){s.policies.unemploymentAid=true;s.policies.socialInsurance=true;s.households.forEach(h=>h.benefit_rate=Math.max(h.benefit_rate||0,.12));s.publicFinance.cash+=6000;},laborRegulation:function(s){s.policies.unionLegal=true;s.policies.workerProtection=true;s.policies.workingHoursLimit=10;s.policies.minimumWage=Math.max(.35,s.policies.minimumWage||0);},investmentState:function(s){s.publicFinance.cash+=12000;s.districts.forEach((d,i)=>{if(i<4){d.road_level=Math.max(1,d.road_level||0);d.access=Math.min(1,(d.access||0)+.08);}if(i<2){d.rail_level=Math.max(1,d.rail_level||0);d.access=Math.min(1,(d.access||0)+.07);}});}};
MS.applyPolicyPreset=function(state,name){const fn=MS.POLICY_PRESETS[name];if(!fn)throw new Error(`Unbekannter Politikpfad: ${name}`);fn(state);return state;};
function summarize(state,seed,preset){const latest=state.metrics.history.at(-1)||{},active=state.firms.filter(f=>f.active),capital=active.reduce((s,f)=>s+f.capital_stock,0),maxPrice=active.reduce((m,f)=>Math.max(m,f.price||0),0),maxCash=active.reduce((m,f)=>Math.max(m,f.cash||0),0),crisisMonths=state.metrics.history.filter(m=>(m.profit||0)<0&&(m.inventory||0)>(m.sales||0)).length;return {seed,preset,tick:state.tick,population:latest.population||0,employment:latest.employment||0,unemploymentRate:latest.unemploymentRate||0,averageWage:latest.averageWage||0,costOfLiving:latest.costOfLiving||0,capital,activeFirms:active.length,bankruptcies:state.events.filter(e=>e.type==='bankruptcy').length,strikeDays:state.politics?state.politics.strikeDays||0:0,organization:state.politics?state.politics.organization||0:0,crisisMonths,maxPrice,maxCash,treasury:state.publicFinance.cash};}
MS.runSingleScenario=function(scenario,seed,ticks,preset){const state=MS.createGameState(clone(scenario),seed);if(MS.initializeSpatialState)MS.initializeSpatialState(state);MS.applyPolicyPreset(state,preset||'laissezFaire');MS.runTicks(state,ticks||240);return summarize(state,seed,preset||'laissezFaire');};
MS.runMonteCarlo=function(scenario,options){const o=Object.assign({seeds:100,ticks:240,startSeed:1,preset:'laissezFaire'},options||{}),rows=[];for(let i=0;i<o.seeds;i++)rows.push(MS.runSingleScenario(scenario,o.startSeed+i,o.ticks,o.preset));return rows;};
MS.diagnoseMonteCarlo=function(rows){const finite=rows.every(r=>Object.values(r).filter(v=>typeof v==='number').every(Number.isFinite)),collapsed=rows.filter(r=>r.activeFirms===0||r.employment<5).length,explosive=rows.filter(r=>r.maxPrice>1e6||r.maxCash>1e9||Math.abs(r.treasury)>1e10).length,unemployment=rows.map(r=>r.unemploymentRate),capital=rows.map(r=>r.capital),spread=a=>a.length?Math.max(...a)-Math.min(...a):0;return {runs:rows.length,finite,collapseRate:rows.length?collapsed/rows.length:0,explosiveRate:rows.length?explosive/rows.length:0,unemploymentSpread:spread(unemployment),capitalSpread:spread(capital),identicalEndStates:spread(unemployment)<1e-10&&spread(capital)<1e-8};};
MS.comparePolicyPresets=function(scenario,seed,ticks){const result={};Object.keys(MS.POLICY_PRESETS).forEach(name=>{result[name]=MS.runSingleScenario(scenario,seed,ticks||240,name);});return result;};
})(typeof globalThis!=='undefined'?globalThis:window);
