(function(root){'use strict';const MS=root.MarxSim=root.MarxSim||{},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const reforms={
    unionLegal:{pressure:0.16,label:'Gewerkschaften legalisieren'},workerProtection:{pressure:0.20,label:'Arbeiterschutz'},workingHoursLimit:{pressure:0.28,label:'Zehnstundentag'},minimumWage:{pressure:0.34,label:'Mindestlohn'},unemploymentAid:{pressure:0.30,label:'Arbeitslosenhilfe'},progressiveTax:{pressure:0.42,label:'Progressive Abgaben'},socialInsurance:{pressure:0.38,label:'Sozialversicherung'}
  }; MS.REFORMS=Object.freeze(reforms);
  function workerRentBurden(state){const workers=state.households.filter(h=>h.class==='workers'),pop=workers.reduce((s,h)=>s+h.population,0)||1;return workers.reduce((s,h)=>s+h.rent_per_capita*h.population,0)/pop/Math.max(0.15,state.economy.averageWage);}
  function concentration(state){const active=state.firms.filter(f=>f.active);const employees=active.reduce((s,f)=>s+f.employees,0);if(!active.length||!employees)return 0;return clamp(active.reduce((s,f)=>s+Math.pow(f.employees/employees,2),0),0,1);}
  function resolveStrikes(state,rng){for(const strike of state.politics.activeStrikes.slice()){const firm=state.firms.find(f=>f.id===strike.firmId);if(!firm){state.politics.activeStrikes.splice(state.politics.activeStrikes.indexOf(strike),1);continue;}state.politics.strikeDays+=firm.employees*22*strike.intensity;strike.monthsLeft-=1;if(strike.monthsLeft>0)continue;const success=rng.next()<clamp(0.35+state.politics.organization*0.45-state.economy.unemploymentRate*0.35,0.12,0.86);firm.strike_intensity=0;if(success){firm.wage_offer*=1.05;state.politics.memory=clamp(state.politics.memory+0.08,0,1);state.politics.discontent*=0.90;}else{state.politics.discontent=clamp(state.politics.discontent+0.04,0,1);state.politics.memory=Math.max(0,state.politics.memory-0.02);}state.events.push({tick:state.tick,type:'strike_resolved',firmId:firm.id,success});state.politics.activeStrikes.splice(state.politics.activeStrikes.indexOf(strike),1);}}
  function maybeStrike(state,rng){if(state.politics.activeStrikes.length||state.politics.organization<0.30||state.politics.discontent<0.42)return;const potential=state.politics.organization*state.politics.discontent;if(rng.next()>potential*0.24)return;const firm=state.firms.filter(f=>f.active&&f.employees>5).sort((a,b)=>b.employees-a.employees)[0];if(!firm)return;const strike={firmId:firm.id,monthsLeft:1+(rng.next()<0.35?1:0),intensity:clamp(0.45+state.politics.organization*0.35,0.45,0.85),demand:state.economy.averageWage/state.economy.costOfLiving<0.32?'wage':'hours'};firm.strike_intensity=strike.intensity;state.politics.activeStrikes.push(strike);state.events.push({tick:state.tick,type:'strike_started',firmId:firm.id,demand:strike.demand});}
  MS.updatePolitics=function updatePolitics(state,rng){if(!state.politics)return state;resolveStrikes(state,rng);const realWage=state.economy.averageWage/Math.max(0.1,state.economy.costOfLiving),rentBurden=workerRentBurden(state),profit=Math.max(0,state.firms.reduce((s,f)=>s+Math.max(0,f.profit),0)),wageBill=Math.max(1,state.firms.reduce((s,f)=>s+f.employees*f.wage_offer,0)),profitVisibility=clamp(profit/wageBill/2.2,0,0.35),hoursStress=clamp(((state.policies.workingHoursLimit||12)-9)/6,0,0.5);
    const disTarget=clamp(state.economy.unemploymentRate*1.05+rentBurden*0.22+clamp(0.34-realWage,0,0.34)*1.25+profitVisibility+hoursStress*0.20-(state.policies.workerProtection?0.06:0)-(state.policies.socialInsurance?0.05:0),0,1);state.politics.discontent+= (disTarget-state.politics.discontent)*0.10;
    const orgTarget=clamp(0.04+concentration(state)*0.34+(state.policies.unionLegal?0.24:0)+state.politics.memory*0.24-state.economy.unemploymentRate*0.08,0,1);state.politics.organization+=(orgTarget-state.politics.organization)*0.07;state.politics.unionDensity=clamp(state.politics.organization*(state.policies.unionLegal?0.82:0.38),0,1);state.politics.reformPressure=clamp(state.politics.discontent*0.55+state.politics.organization*0.42+state.economy.unemploymentRate*0.20,0,1);
    state.politics.support.socialReform=clamp(0.18+state.politics.discontent*0.42,0,0.8);state.politics.support.socialist=clamp(0.08+state.politics.discontent*state.politics.organization*0.70,0,0.75);state.politics.support.laissezFaire=clamp(0.58-state.politics.discontent*0.42,0.08,0.72);state.politics.support.authoritarian=clamp(0.10+state.politics.discontent*(1-state.politics.organization)*0.25,0.05,0.40);maybeStrike(state,rng);return state;};
  MS.enactPolicy=function enactPolicy(state,id){const r=reforms[id];if(!r)return{ok:false,reason:'unknown'};if(state.politics.reformPressure<r.pressure)return{ok:false,reason:'pressure',required:r.pressure};if(id==='unionLegal')state.policies.unionLegal=true;if(id==='workerProtection')state.policies.workerProtection=true;if(id==='workingHoursLimit')state.policies.workingHoursLimit=10;if(id==='minimumWage')state.policies.minimumWage=Math.max(state.policies.minimumWage,state.economy.costOfLiving*0.27);if(id==='unemploymentAid'){state.policies.unemploymentAid=true;state.households.forEach(h=>h.benefit_rate=(h.benefit_rate||0)+0.08);}if(id==='progressiveTax'){state.policies.progressiveTax=true;state.policies.corporateTaxRate=Math.max(state.policies.corporateTaxRate,0.14);}if(id==='socialInsurance'){state.policies.socialInsurance=true;state.households.forEach(h=>h.benefit_rate=(h.benefit_rate||0)+0.04);}state.politics.legitimacy=clamp(state.politics.legitimacy+0.04,0,1);state.politics.reformPressure*=0.72;state.events.push({tick:state.tick,type:'reform_enacted',policy:id});return{ok:true,policy:id};};
})(typeof globalThis!=='undefined'?globalThis:window);
